/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as MetaRouteImport } from './routes/meta'
import { Route as KaibaLabsRouteImport } from './routes/kaiba-labs'
import { Route as ComoComprarRouteImport } from './routes/como-comprar'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminArticlesNewRouteImport } from './routes/admin.articles.new'
import { Route as AdminProductsEditIdRouteImport } from './routes/admin.products.edit.$id'
import { Route as AdminArticlesEditIdRouteImport } from './routes/admin.articles.edit.$id'

const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaRoute = MetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const KaibaLabsRoute = KaibaLabsRouteImport.update({
  id: '/kaiba-labs',
  path: '/kaiba-labs',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoComprarRoute = ComoComprarRouteImport.update({
  id: '/como-comprar',
  path: '/como-comprar',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminArticlesRoute,
} as any)
const AdminProductsEditIdRoute = AdminProductsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminArticlesEditIdRoute = AdminArticlesEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminArticlesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/catalog': typeof CatalogRoute
  '/catalogo': typeof CatalogoRoute
  '/como-comprar': typeof ComoComprarRoute
  '/kaiba-labs': typeof KaibaLabsRoute
  '/meta': typeof MetaRoute
  '/noticias': typeof NoticiasRoute
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/articles/edit/$id': typeof AdminArticlesEditIdRoute
  '/admin/products/edit/$id': typeof AdminProductsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/catalog': typeof CatalogRoute
  '/catalogo': typeof CatalogoRoute
  '/como-comprar': typeof ComoComprarRoute
  '/kaiba-labs': typeof KaibaLabsRoute
  '/meta': typeof MetaRoute
  '/noticias': typeof NoticiasRoute
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/articles/edit/$id': typeof AdminArticlesEditIdRoute
  '/admin/products/edit/$id': typeof AdminProductsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/catalog': typeof CatalogRoute
  '/catalogo': typeof CatalogoRoute
  '/como-comprar': typeof ComoComprarRoute
  '/kaiba-labs': typeof KaibaLabsRoute
  '/meta': typeof MetaRoute
  '/noticias': typeof NoticiasRoute
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/articles/edit/$id': typeof AdminArticlesEditIdRoute
  '/admin/products/edit/$id': typeof AdminProductsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/carrito'
    | '/catalog'
    | '/catalogo'
    | '/como-comprar'
    | '/kaiba-labs'
    | '/meta'
    | '/noticias'
    | '/admin/articles'
    | '/admin/inventory'
    | '/admin/media'
    | '/admin/products'
    | '/admin/settings'
    | '/producto/$slug'
    | '/admin/'
    | '/admin/articles/new'
    | '/admin/products/new'
    | '/admin/articles/edit/$id'
    | '/admin/products/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrito'
    | '/catalog'
    | '/catalogo'
    | '/como-comprar'
    | '/kaiba-labs'
    | '/meta'
    | '/noticias'
    | '/admin/articles'
    | '/admin/inventory'
    | '/admin/media'
    | '/admin/products'
    | '/admin/settings'
    | '/producto/$slug'
    | '/admin'
    | '/admin/articles/new'
    | '/admin/products/new'
    | '/admin/articles/edit/$id'
    | '/admin/products/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/carrito'
    | '/catalog'
    | '/catalogo'
    | '/como-comprar'
    | '/kaiba-labs'
    | '/meta'
    | '/noticias'
    | '/admin/articles'
    | '/admin/inventory'
    | '/admin/media'
    | '/admin/products'
    | '/admin/settings'
    | '/producto/$slug'
    | '/admin/'
    | '/admin/articles/new'
    | '/admin/products/new'
    | '/admin/articles/edit/$id'
    | '/admin/products/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CarritoRoute: typeof CarritoRoute
  CatalogRoute: typeof CatalogRoute
  CatalogoRoute: typeof CatalogoRoute
  ComoComprarRoute: typeof ComoComprarRoute
  KaibaLabsRoute: typeof KaibaLabsRoute
  MetaRoute: typeof MetaRoute
  NoticiasRoute: typeof NoticiasRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta': {
      id: '/meta'
      path: '/meta'
      fullPath: '/meta'
      preLoaderRoute: typeof MetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kaiba-labs': {
      id: '/kaiba-labs'
      path: '/kaiba-labs'
      fullPath: '/kaiba-labs'
      preLoaderRoute: typeof KaibaLabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-comprar': {
      id: '/como-comprar'
      path: '/como-comprar'
      fullPath: '/como-comprar'
      preLoaderRoute: typeof ComoComprarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof AdminArticlesRoute
    }
    '/admin/products/edit/$id': {
      id: '/admin/products/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/products/edit/$id'
      preLoaderRoute: typeof AdminProductsEditIdRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/articles/edit/$id': {
      id: '/admin/articles/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/articles/edit/$id'
      preLoaderRoute: typeof AdminArticlesEditIdRouteImport
      parentRoute: typeof AdminArticlesRoute
    }
  }
}

interface AdminArticlesRouteChildren {
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
  AdminArticlesEditIdRoute: typeof AdminArticlesEditIdRoute
}

const AdminArticlesRouteChildren: AdminArticlesRouteChildren = {
  AdminArticlesNewRoute: AdminArticlesNewRoute,
  AdminArticlesEditIdRoute: AdminArticlesEditIdRoute,
}

const AdminArticlesRouteWithChildren = AdminArticlesRoute._addFileChildren(
  AdminArticlesRouteChildren,
)

interface AdminProductsRouteChildren {
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsEditIdRoute: typeof AdminProductsEditIdRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsEditIdRoute: AdminProductsEditIdRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteChildren {
  AdminArticlesRoute: typeof AdminArticlesRouteWithChildren
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArticlesRoute: AdminArticlesRouteWithChildren,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CarritoRoute: CarritoRoute,
  CatalogRoute: CatalogRoute,
  CatalogoRoute: CatalogoRoute,
  ComoComprarRoute: ComoComprarRoute,
  KaibaLabsRoute: KaibaLabsRoute,
  MetaRoute: MetaRoute,
  NoticiasRoute: NoticiasRoute,
  ProductoSlugRoute: ProductoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
